version: "3.7"

services:
  posse-app:
    image: posse:latest
    build: ./
    container_name: posse
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    restart: unless-stopped
