version: "3.7"

services:
  posse-app:
    image: posse:latest
    build: ./
    container_name: posse
    ports:
      - 3000:3000
    environment:
      VIRTUAL_HOST: posse.redalemeden.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: posse.redalemeden.com
      LETSENCRYPT_EMAIL: letsencrypt@reda.fastmail.com
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
